baseURL: "https://kmclester.com/"
title: Kyle's Blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: G-06XBWZ9STS

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
                - name: Contact
                  url: contact/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Personal blog"
    author: Kyle McLester

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true


    homeInfoParams:
        Title: "Welcome!"
        Content: >
            This website is going to act as a dumping ground for things I'm learning or working on.
            Feel free to take a peek

    socialIcons:
        - name: github
          url: "https://github.com/kmcleste"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://github.com/kmcleste/personal-blog/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    analytics:
        google:
            SiteVerificationTag: "G-06XBWZ9STS"


taxonomies:
    category: categories
    tag: tags
    series: series
    contact: contact

markup:
    goldmark:
        renderer:
            unsafe: true
            
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
