[build]
    publish = "public"
    command = "hugo --theme=PaperMod --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.92.1"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"